spring.application.name=enterprise-helpdesk-api

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/unsa_helpdesk
spring.datasource.username=root
spring.datasource.password=Abc1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.secret=TuClaveSecretaSuperLargaDeMinimo32CaracteresParaHS256AquiPongoMas
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
